dist: xenial
language: node_js
cache: yarn
node_js:
  - "lts/*"
stages:
  - lint
  - unit-test
jobs:
  include:
    - stage: lint
      install: npm install eslint
      script: yarn lint
    - stage: unit-test
      install: yarn
      script: yarn test
