dist: xenial
language: node_js
cache: yarn
node_js:
  - "lts/*"
stages:
  - lint
  - unit-test
jobs:
  include:
    - stage: lint
      install: yarn install
      script: yarn lint
    - stage: unit-test
      install: yarn install
      script: yarn test
